/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nykVn4SWaRz
 */
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"
import { CardContent, Card } from "@/components/ui/card"

export function landing() {
  return (
    (<div key="1" className="flex flex-col min-h-screen">
      <section className="w-full h-[500px] md:h-[700px]">
        <img
          alt="Welcome"
          className="object-cover w-full h-full"
          height="1080"
          src="/placeholder.svg"
          style={{
            aspectRatio: "1920/1080",
            objectFit: "cover",
          }}
          width="1920" />
        <div
          className="absolute inset-0 flex flex-col items-center justify-center bg-black bg-opacity-50 text-white p-4">
          <h1 className="text-3xl md:text-5xl font-bold">Welcome to Our Store</h1>
          <p className="text-lg md:text-2xl mt-4">Discover the best deals and amazing discounts.</p>
        </div>
      </section>
      <section className="w-full py-12">
        <Carousel className="w-full max-w-5xl mx-auto" infinite>
          <CarouselContent>
            <CarouselItem>
              <img
                alt="Brand 1"
                className="object-cover w-20 h-20 mx-auto"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100" />
            </CarouselItem>
            <CarouselItem>
              <img
                alt="Brand 2"
                className="object-cover w-20 h-20 mx-auto"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100" />
            </CarouselItem>
            <CarouselItem>
              <img
                alt="Brand 3"
                className="object-cover w-20 h-20 mx-auto"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100" />
            </CarouselItem>
          </CarouselContent>
          <CarouselPrevious />
          <CarouselNext />
        </Carousel>
      </section>
      <section className="w-full py-12">
        <div className="container grid grid-cols-1 md:grid-cols-4 gap-6 px-4 md:px-6">
          <Card>
            <CardContent className="flex flex-col items-center justify-center p-6">
              <h2 className="text-2xl font-bold">Clothing Item 1</h2>
              <p className="text-lg mt-2">Category: Shirts</p>
              <p className="text-lg mt-2 font-bold">Price: $49.99</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex flex-col items-center justify-center p-6">
              <h2 className="text-2xl font-bold">Clothing Item 2</h2>
              <p className="text-lg mt-2">Category: Pants</p>
              <p className="text-lg mt-2 font-bold">Price: $59.99</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex flex-col items-center justify-center p-6">
              <h2 className="text-2xl font-bold">Clothing Item 3</h2>
              <p className="text-lg mt-2">Category: Jackets</p>
              <p className="text-lg mt-2 font-bold">Price: $99.99</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex flex-col items-center justify-center p-6">
              <h2 className="text-2xl font-bold">Clothing Item 4</h2>
              <p className="text-lg mt-2">Category: Shoes</p>
              <p className="text-lg mt-2 font-bold">Price: $79.99</p>
            </CardContent>
          </Card>
        </div>
      </section>
      <section className="w-full py-12">
        <div className="container grid grid-cols-2 md:grid-cols-4 gap-6 px-4 md:px-6" />
      </section>
      <section className="w-full h-[500px] md:h-[700px] relative">
        <img
          alt="Limited Time Offer"
          className="object-cover w-full h-full"
          height="1080"
          src="/placeholder.svg"
          style={{
            aspectRatio: "1920/1080",
            objectFit: "cover",
          }}
          width="1920" />
        <div
          className="absolute inset-0 flex flex-col items-center justify-center bg-black bg-opacity-50 text-white p-4">
          <h1 className="text-3xl md:text-5xl font-bold">Limited Time Offer</h1>
          <p className="text-lg md:text-2xl mt-4">Grab the deal before it's gone!</p>
        </div>
      </section>
    </div>)
  );
}
