/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/anP4lQtvilA
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuRadioItem, DropdownMenuRadioGroup, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import Link from "next/link"

export function Men() {
  return (
    (<section key="1" className="w-full py-12 md:py-24">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col gap-4 md:gap-8">
          <div className="grid gap-1">
            <h1 className="font-bold tracking-tight md:text-4xl">Summer Collection</h1>
            <p className="text-gray-500 dark:text-gray-400">
              Hot Picks from the Summer Collection: Embrace the Season in Style!
            </p>
          </div>
          <div className="flex items-center gap-4 md:gap-8">
            <form className="flex-1">
              <div
                className="flex items-center gap-2 border border-gray-200 rounded-lg dark:border-gray-800 dark:border-gray-800">
                <SearchIcon className="h-4 w-4 ml-2.5 text-gray-500 dark:text-gray-400" />
                <Input
                  className="w-36 h-10 border-0 appearance-none bg-transparent focus:outline-none"
                  placeholder="Search"
                  type="search" />
              </div>
            </form>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button className="shrink-0" variant="outline">
                  <ArrowUpDownIcon className="w-4 h-4 mr-2" />
                  Sort by
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-[200px]">
                <DropdownMenuRadioGroup value="featured">
                  <DropdownMenuRadioItem value="featured">Featured</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="Newest">Newest</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="low">Price: Low to High</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="high">Price: High to Low</DropdownMenuRadioItem>
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>
            <div className="flex items-center gap-2">
              <Input
                className="w-20 h-10 border border-gray-200 rounded-lg dark:border-gray-800 dark:border-gray-800"
                placeholder="Min"
                type="number" />
              <span>-</span>
              <Input
                className="w-20 h-10 border border-gray-200 rounded-lg dark:border-gray-800 dark:border-gray-800"
                placeholder="Max"
                type="number" />
            </div>
          </div>
          <div className="grid sm:grid-cols-2 md:grid-cols-1 lg:grid-cols-3 gap-8">
            <div className="relative group">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View</span>
              </Link>
              <img
                alt="Cover image"
                className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                height={200}
                src="/placeholder.svg"
                width={200} />
              <div className="flex-1 py-4">
                <h3 className="font-semibold tracking-tight">Beach Bliss Flip-Flops</h3>
                <small className="text-sm leading-none text-gray-500 dark:text-gray-400">Comfortable Footwear</small>
                <h4 className="font-semibold">$19.99</h4>
              </div>
            </div>
            <div className="relative group">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View</span>
              </Link>
              <img
                alt="Cover image"
                className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                height={200}
                src="/placeholder.svg"
                width={200} />
              <div className="flex-1 py-4">
                <h3 className="font-semibold tracking-tight">Sunset Shades Sunglasses</h3>
                <small className="text-sm leading-none text-gray-500 dark:text-gray-400">UV Protection Eyewear</small>
                <h4 className="font-semibold">$29.99</h4>
              </div>
            </div>
            <div className="relative group">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View</span>
              </Link>
              <img
                alt="Cover image"
                className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                height={200}
                src="/placeholder.svg"
                width={200} />
              <div className="flex-1 py-4">
                <h3 className="font-semibold tracking-tight">Cool Breeze Portable Fan</h3>
                <small className="text-sm leading-none text-gray-500 dark:text-gray-400">On-the-Go Cooling</small>
                <h4 className="font-semibold">$14.99</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function ArrowUpDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m21 16-4 4-4-4" />
      <path d="M17 20V4" />
      <path d="m3 8 4-4 4" />
      <path d="M7 4v16" />
    </svg>)
  );
}
